# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 675ea4f94dc5f32ec8cd1117bab9b0b79138cd4f501ae895d6bfd8ac51854c7b10017ddf5645facffeeb2a36d9cde6844e2481034e44c76f338c0e0278fc00c6

test:
  secret_key_base: 8c00956f3c01dc4348c43a371c56615ec983d7b8549362c8c521b4575563810c0573634fe44c9cef61eecef2f4bc9aa0d1b7e1b9886f3fa4fcb93a2ece3cfbf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
